import { Link } from "@/i18n/routing";
import { brandNameToSlug } from "@/lib/brand-slug";
import type { HomepageViewModel } from "@/lib/homepage-view-model";

/**
 * Discover Brands — "Inside the Brand" (V22 source: src/App.tsx,
 * Brands()). Position: after SAVO Spotlight, matching V22's exact
 * source order (Spotlight → Brands → DiscoverTogether — the latter
 * not yet migrated, out of this task's scope).
 *
 * Real data only — `brands` (name/count) comes from the same
 * canonical `Product.brandName` field the real /brands page groups
 * by. `catalogBrands` (Phase 2) supplies real logo/cover/description
 * when a matching Brand row exists — matched by name, zero automatic
 * relation assumed. Fallback hierarchy per card: coverImageUrl →
 * logoUrl (contained, clean surface) → monogram (same canonical
 * treatment as the real /brands page). Never a random product photo,
 * stock image, or V22 demo art.
 *
 * Routing correctness fix: `data.brands[].slug` is generated by a
 * local slugify() inside homepage-view-model.ts that diverges from
 * the canonical brandNameToSlug() the real /brands/[slug] route uses
 * (different "&" handling) — so this component recomputes the slug
 * via the canonical helper at render time instead of trusting the
 * pre-computed one, guaranteeing every card links to a real,
 * resolvable brand page.
 *
 * V22's per-brand "sub" (e.g. "Sound Engineering") has no real SAVO
 * field to back it — SAVO brands are a plain string on Product with
 * no separate model/description/tagline/cover-image. Omitted
 * gracefully rather than invented, exactly like the real /brands
 * page's own "Featured brands" already does. Image fallback reuses
 * that same page's canonical treatment: a first-letter monogram with
 * a rotating accent, not a random product photo or stock image.
 */
const ACCENTS = ["teal", "gold", "fire"] as const;
const CARD_COUNT = 6;

export function DiscoverBrands({ brands, catalogBrands, locale }: { brands: HomepageViewModel["brands"]; catalogBrands: HomepageViewModel["catalogBrands"]; locale: string }) {
  const isArabic = locale === "ar";
  const shown = brands.slice(0, CARD_COUNT);
  if (shown.length === 0) return null;
  const catalogByLowerName = new Map(catalogBrands.map((b) => [b.name.toLowerCase(), b]));

  return (
    <section className="savo-discoverbrands">
      <div className="savo-discoverbrands-head">
        <p className="savo-products-eyebrow">{isArabic ? "اكتشف العلامات" : "Discover Brands"}</p>
        <h2 className="savo-discoverbrands-title">{isArabic ? "داخل العلامة التجارية" : "Inside the Brand"}</h2>
        <Link href="/brands" className="savo-discoverbrands-viewall">{isArabic ? "كل العلامات ←" : "All brands →"}</Link>
      </div>

      <div className="savo-discoverbrands-row">
        {shown.map((b, i) => {
          const slug = brandNameToSlug(b.name);
          const accent = ACCENTS[i % ACCENTS.length];
          const catalog = catalogByLowerName.get(b.name.toLowerCase());
          const displayName = isArabic && catalog?.nameAr ? catalog.nameAr : b.name;
          return (
            <Link key={slug} href={`/brands/${slug}`} className={`savo-discoverbrands-card savo-discoverbrands-card--${accent}${i === 0 ? " is-featured" : ""}`}>
              {catalog?.coverImageUrl ? (
                <img src={catalog.coverImageUrl} alt={displayName} className="savo-discoverbrands-cover" />
              ) : catalog?.logoUrl ? (
                <span className="savo-discoverbrands-logo-fallback"><img src={catalog.logoUrl} alt={displayName} /></span>
              ) : (
                <span className="savo-discoverbrands-monogram">{b.name[0]?.toUpperCase()}</span>
              )}
              <span className="savo-discoverbrands-scrim" />
              <span className="savo-discoverbrands-name">{displayName}</span>
              <span className="savo-discoverbrands-explore">{isArabic ? "استكشف ←" : "Explore →"}</span>
            </Link>
          );
        })}
      </div>
    </section>
  );
}
