import { prisma } from "@/lib/prisma";
import { NotificationService } from "@/lib/notifications/service";
import { PushNotificationService } from "@/lib/services/push-notification-service";

/**
 * MarketingAutomationService — Phase 6.7
 *
 * Real-time triggers (AFTER_PURCHASE, PRODUCT_RESTOCK) are called
 * directly from the code that already knows the event just happened.
 * Time-based triggers (CUSTOMER_INACTIVE, CART_ABANDONED, BIRTHDAY) are
 * scanned by checkScheduledTriggers(), written for a scheduled job —
 * same honest scope note as SubscriptionService (Phase 6.6): no cron
 * exists in this Next.js app yet, so it's also safely triggerable
 * on-demand.
 */
export class MarketingAutomationService {
  private static async execute(automationId: string, userId: string) {
    const automation = await prisma.marketingAutomation.findUnique({ where: { id: automationId } });
    if (!automation || !automation.active) return;

    let actionTaken: string;

    if (automation.action === "EMAIL") {
      const user = await prisma.user.findUnique({ where: { id: userId }, select: { email: true } });
      await NotificationService.dispatch({
        type: "MARKETING_AUTOMATION",
        recipientUserId: userId,
        recipientEmail: user?.email,
        data: { automationName: automation.name, trigger: automation.trigger },
      });
      actionTaken = "Email dispatched";
    } else if (automation.action === "DISCOUNT") {
      const code = `${automation.trigger.slice(0, 4)}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
      await prisma.promoCode.create({
        data: { code, description: `Auto-generated by "${automation.name}"`, percentOff: 10, maxUses: 1, isActive: true },
      });
      actionTaken = `Promo code ${code} issued (10% off, single use)`;
    } else {
      const pushResult = await PushNotificationService.sendToUser(userId, automation.name, `You have a new offer from Saveo`);
      actionTaken = pushResult.attempted === 0
        ? "No registered devices to push to"
        : pushResult.configured
        ? `Push sent to ${pushResult.sent}/${pushResult.attempted} device(s)`
        : `Push attempted for ${pushResult.attempted} device(s) — not sent (FCM/APNs credentials not configured)`;
    }

    await prisma.automationExecution.create({ data: { automationId, userId, actionTaken } });
  }

  /** Real-time trigger — call right after a successful checkout. */
  static async checkAfterPurchase(userId: string) {
    const automations = await prisma.marketingAutomation.findMany({ where: { trigger: "AFTER_PURCHASE", active: true } });
    for (const automation of automations) {
      await this.execute(automation.id, userId).catch(() => {});
    }
  }

  /** Real-time trigger — call when a product's stock goes from 0 to positive. Notifies customers who favorited this product. */
  static async checkProductRestock(productId: string) {
    const automations = await prisma.marketingAutomation.findMany({ where: { trigger: "PRODUCT_RESTOCK", active: true } });
    if (automations.length === 0) return;

    const interestedUsers = await prisma.favorite.findMany({ where: { productId }, select: { userId: true } });
    for (const automation of automations) {
      for (const { userId } of interestedUsers) {
        await this.execute(automation.id, userId).catch(() => {});
      }
    }
  }

  /** Scans for CUSTOMER_INACTIVE / CART_ABANDONED / BIRTHDAY — meant for a scheduled job. */
  static async checkScheduledTriggers() {
    const automations = await prisma.marketingAutomation.findMany({ where: { active: true, trigger: { in: ["CUSTOMER_INACTIVE", "CART_ABANDONED", "BIRTHDAY"] } } });
    let triggered = 0;

    for (const automation of automations) {
      const conditions = (automation.conditions as any) ?? {};

      if (automation.trigger === "CUSTOMER_INACTIVE") {
        const inactiveDays = conditions.inactiveDays ?? 30;
        const cutoff = new Date();
        cutoff.setDate(cutoff.getDate() - inactiveDays);
        const inactiveUsers = await prisma.user.findMany({
          where: { role: "CUSTOMER", orders: { none: { createdAt: { gte: cutoff } } } },
          select: { id: true },
          take: 200,
        });
        for (const u of inactiveUsers) {
          await this.execute(automation.id, u.id).catch(() => {});
          triggered++;
        }
      }
      // CART_ABANDONED and BIRTHDAY need dedicated cart-session and
      // birthdate data this schema doesn't track yet — left as a
      // documented gap rather than a fake implementation.
    }

    return { triggered };
  }
}
